"""add order channel (dine_in vs online)

Revision ID: 9fad1e42fe69
Revises: 2c94d6531e6e
Create Date: 2026-07-29 18:44:42.579797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fad1e42fe69'
down_revision: Union[str, Sequence[str], None] = '2c94d6531e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default required: `orders` already has rows in the real DB, and
    # a NOT NULL column with no default can't be added to a non-empty table.
    op.add_column(
        'orders',
        sa.Column(
            'channel',
            sa.Enum('dine_in', 'online', name='orderchannelenum', native_enum=False, length=20),
            server_default='dine_in',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'channel')
    # ### end Alembic commands ###
