"""org scheduled closure access_ends_at

Revision ID: 2c94d6531e6e
Revises: 584eead0f022
Create Date: 2026-07-23 20:40:23.137943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c94d6531e6e'
down_revision: Union[str, Sequence[str], None] = '584eead0f022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('access_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'access_ends_at')
    # ### end Alembic commands ###
