"""Demo engagement data for the "Demo Bistro Group" organization only.

Populates Orders, Invoices/Payments, Reservations, and Loyalty accounts for
every active branch of the `demo-bistro-group` org so the admin dashboards
(Live Orders, Payments, Reservations, Loyalty, Analytics, Org Analytics) have
something realistic to show when logged in as the demo super_admin.

Idempotent: every `Order.display_code` this module creates is prefixed with
`ENG-` (distinct from the real `ORD-...` codes generated by
`app/services/orders.py::_display_code()`). Before inserting anything for a
branch, we check whether any `ENG-` orders already exist for that
`restaurant_id` and skip straight to the next branch if so — safe to call
`seed()` any number of times without duplicating rows.

Run with (from backend/, venv active):
    python -m app.seed_demo_data.engagement
"""

import asyncio
import random
from datetime import date, datetime, time, timedelta, timezone
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import AsyncSessionLocal
from app.models.billing import (
    Invoice,
    InvoiceOrder,
    InvoiceStatusEnum,
    Payment,
    PaymentMethodEnum,
    PaymentStatusEnum,
)
from app.models.menu import MenuItem
from app.models.order import Order, OrderItem, OrderStatusEnum
from app.models.organization import Organization
from app.models.promotions import LoyaltyAccount
from app.models.reservation import Reservation, ReservationStatusEnum
from app.models.restaurant import Restaurant
from app.models.table import RestaurantTable

DEMO_ORG_SLUG = "demo-bistro-group"

# Distinctive marker separating this module's rows from real / other-seeded
# orders (services/orders.py uses "ORD-...").
ENGAGEMENT_ORDER_PREFIX = "ENG-"

_ORDER_STATUS_WEIGHTS: list[tuple[OrderStatusEnum, int]] = [
    (OrderStatusEnum.served, 60),
    (OrderStatusEnum.received, 10),
    (OrderStatusEnum.preparing, 10),
    (OrderStatusEnum.ready, 10),
    (OrderStatusEnum.cancelled, 4),
]

_PAYMENT_METHODS = [PaymentMethodEnum.cash, PaymentMethodEnum.card, PaymentMethodEnum.upi]

_GUEST_NAMES = [
    "Aarav Sharma", "Priya Nair", "Rohan Mehta", "Sneha Kapoor", "Vikram Rao",
    "Ananya Iyer", "Karan Malhotra", "Ishita Gupta", "Arjun Singh", "Divya Menon",
    "Rahul Verma", "Neha Joshi", "Aditya Kumar", "Pooja Reddy", "Siddharth Bose",
    "Kavya Pillai", "Manish Agarwal", "Ritu Chawla", "Nikhil Desai", "Tanvi Shah",
]

_RESERVATION_NOTES = [
    "Window seat if possible",
    "Anniversary dinner",
    "Birthday — please bring a candle",
    "Wheelchair access needed",
    "Quiet corner preferred",
    "",
    "",
]


def _next_engagement_code(counter: list[int]) -> str:
    """Monotonic, globally-unique-enough code: prefix + timestamp + running
    counter, so two branches processed in the same second never collide."""
    counter[0] += 1
    ts = int(datetime.now(timezone.utc).timestamp() * 1000)
    return f"{ENGAGEMENT_ORDER_PREFIX}{ts:x}{counter[0]:04d}".upper()


def _random_phone(rng: random.Random) -> str:
    return f"+91{rng.randint(6000000000, 9999999999)}"


async def _seed_branch(db: AsyncSession, restaurant: Restaurant, code_counter: list[int]) -> dict[str, int]:
    """Seeds one branch's worth of engagement data. Returns a dict of counts
    created (all zero if the branch was already seeded or had no usable menu
    items/tables to build orders from)."""

    counts = {"orders": 0, "order_items": 0, "invoices": 0, "payments": 0, "reservations": 0, "loyalty": 0}

    existing = await db.execute(
        select(Order.id).where(
            Order.restaurant_id == restaurant.id,
            Order.display_code.like(f"{ENGAGEMENT_ORDER_PREFIX}%"),
        ).limit(1)
    )
    if existing.scalar_one_or_none():
        print(f"  [{restaurant.slug}] engagement data already seeded — skipping.")
        return counts

    tables_result = await db.execute(
        select(RestaurantTable).where(
            RestaurantTable.restaurant_id == restaurant.id,
            RestaurantTable.is_active.is_(True),
        )
    )
    tables = list(tables_result.scalars().all())

    items_result = await db.execute(
        select(MenuItem).where(
            MenuItem.restaurant_id == restaurant.id,
            MenuItem.is_active.is_(True),
            MenuItem.is_available.is_(True),
        )
    )
    menu_items = list(items_result.scalars().all())

    created_throwaway_table = False
    created_throwaway_item = False

    if not tables:
        print(f"  [{restaurant.slug}] no active tables found — creating 1 throwaway table to unblock testing.")
        table = RestaurantTable(restaurant_id=restaurant.id, code="ENG-T1")
        db.add(table)
        await db.flush()
        tables = [table]
        created_throwaway_table = True

    if not menu_items:
        print(f"  [{restaurant.slug}] no active menu items found — creating 1 throwaway item to unblock testing.")
        from app.models.menu import MenuCategory

        category = MenuCategory(restaurant_id=restaurant.id, name="Engagement Placeholder", slug="eng-placeholder", sort_order=999)
        db.add(category)
        await db.flush()
        item = MenuItem(
            restaurant_id=restaurant.id,
            category_id=category.id,
            name="Engagement Placeholder Dish",
            description="Throwaway item created only to unblock demo-data testing.",
            base_price=Decimal("10.00"),
            sort_order=999,
        )
        db.add(item)
        await db.flush()
        menu_items = [item]
        created_throwaway_item = True

    rng = random.Random(f"engagement-{restaurant.id}")
    now = datetime.now(timezone.utc)

    # ---------- Orders ----------
    num_orders = rng.randint(25, 35)
    created_orders: list[Order] = []
    for i in range(num_orders):
        # Spread across last 14 days; force a handful onto "today".
        if i < 4:
            days_ago = 0
        else:
            days_ago = rng.randint(0, 13)
        created_at = now - timedelta(
            days=days_ago,
            hours=rng.randint(0, 23) if days_ago > 0 else rng.randint(0, now.hour) if now.hour > 0 else 0,
            minutes=rng.randint(0, 59),
        )

        status = rng.choices(
            [s for s, _ in _ORDER_STATUS_WEIGHTS],
            weights=[w for _, w in _ORDER_STATUS_WEIGHTS],
            k=1,
        )[0]
        table = rng.choice(tables)

        order = Order(
            restaurant_id=restaurant.id,
            table_id=table.id,
            display_code=_next_engagement_code(code_counter),
            status=status,
            note="",
            subtotal=0,
            total=0,
            created_at=created_at,
        )

        num_lines = rng.randint(1, 4)
        subtotal = Decimal("0")
        for _ in range(num_lines):
            menu_item = rng.choice(menu_items)
            quantity = rng.randint(1, 3)
            unit_price = menu_item.base_price
            line_total = unit_price * quantity
            order.items.append(
                OrderItem(
                    menu_item_id=menu_item.id,
                    name_snapshot=menu_item.name,
                    unit_price_snapshot=unit_price,
                    quantity=quantity,
                    line_total=line_total,
                )
            )
            subtotal += line_total

        order.subtotal = subtotal
        order.total = subtotal
        db.add(order)
        created_orders.append(order)
        counts["orders"] += 1
        counts["order_items"] += num_lines

    await db.flush()

    # ---------- Invoices & Payments (for a subset of served orders) ----------
    served_orders = [o for o in created_orders if o.status == OrderStatusEnum.served]
    rng.shuffle(served_orders)
    num_invoices = min(len(served_orders), rng.randint(8, 10))
    for order in served_orders[:num_invoices]:
        tax_rate = Decimal("5.00")
        tax_amount = (order.subtotal * tax_rate / Decimal("100")).quantize(Decimal("0.01"))
        total = order.subtotal + tax_amount

        invoice = Invoice(
            restaurant_id=restaurant.id,
            table_id=order.table_id,
            subtotal=order.subtotal,
            tax_rate=tax_rate,
            tax_amount=tax_amount,
            total=total,
            status=InvoiceStatusEnum.paid,
            created_at=order.created_at + timedelta(minutes=rng.randint(20, 60)),
        )
        db.add(invoice)
        await db.flush()

        db.add(InvoiceOrder(invoice_id=invoice.id, order_id=order.id))

        method = rng.choice(_PAYMENT_METHODS)
        db.add(
            Payment(
                invoice_id=invoice.id,
                method=method,
                amount=total,
                status=PaymentStatusEnum.succeeded,
                created_at=invoice.created_at,
            )
        )
        counts["invoices"] += 1
        counts["payments"] += 1

    # ---------- Reservations ----------
    num_reservations = rng.randint(4, 6)
    today = date.today()
    for i in range(num_reservations):
        is_upcoming = i % 2 == 0
        if is_upcoming:
            res_date = today + timedelta(days=rng.randint(1, 14))
            res_status = rng.choice([ReservationStatusEnum.confirmed, ReservationStatusEnum.pending])
        else:
            res_date = today - timedelta(days=rng.randint(1, 7))
            res_status = ReservationStatusEnum.confirmed

        hour = rng.choice([12, 13, 18, 19, 20, 21])
        minute = rng.choice([0, 30])

        db.add(
            Reservation(
                restaurant_id=restaurant.id,
                reference_code=_next_engagement_code(code_counter).replace(ENGAGEMENT_ORDER_PREFIX, "ENGR-"),
                name=rng.choice(_GUEST_NAMES),
                phone=_random_phone(rng),
                party_size=rng.randint(2, 8),
                date=res_date,
                time=time(hour, minute),
                note=rng.choice(_RESERVATION_NOTES),
                status=res_status,
            )
        )
        counts["reservations"] += 1

    # ---------- Loyalty accounts ----------
    num_loyalty = rng.randint(5, 8)
    used_phones: set[str] = set()
    names_pool = list(_GUEST_NAMES)
    rng.shuffle(names_pool)
    for i in range(num_loyalty):
        phone = _random_phone(rng)
        while phone in used_phones:
            phone = _random_phone(rng)
        used_phones.add(phone)

        db.add(
            LoyaltyAccount(
                restaurant_id=restaurant.id,
                phone=phone,
                name=names_pool[i % len(names_pool)],
                points=rng.randint(20, 500),
            )
        )
        counts["loyalty"] += 1

    await db.flush()

    if created_throwaway_table:
        print(f"  [{restaurant.slug}] note: throwaway table 'ENG-T1' was created — remove once real table seed has run.")
    if created_throwaway_item:
        print(f"  [{restaurant.slug}] note: throwaway menu item 'Engagement Placeholder Dish' was created — remove once real menu seed has run.")

    return counts


async def seed(db: AsyncSession) -> None:
    """Seeds Orders/Invoices/Payments/Reservations/LoyaltyAccounts for every
    active branch of the 'Demo Bistro Group' organization. Idempotent per
    branch (see `_seed_branch`). Never touches any other organization."""

    org_result = await db.execute(select(Organization).where(Organization.slug == DEMO_ORG_SLUG))
    org = org_result.scalar_one_or_none()
    if not org:
        print(f"Organization '{DEMO_ORG_SLUG}' not found — nothing to seed.")
        return

    branches_result = await db.execute(
        select(Restaurant).where(Restaurant.organization_id == org.id, Restaurant.is_active.is_(True))
    )
    branches = list(branches_result.scalars().all())
    if not branches:
        print(f"No active branches found for organization '{DEMO_ORG_SLUG}' — nothing to seed.")
        return

    code_counter = [0]
    total_counts: dict[str, dict[str, int]] = {}
    for branch in branches:
        print(f"Seeding engagement data for branch '{branch.slug}' ({branch.name})...")
        counts = await _seed_branch(db, branch, code_counter)
        total_counts[branch.slug] = counts

    await db.commit()

    print("\nEngagement seed summary:")
    for slug, counts in total_counts.items():
        print(
            f"  {slug}: {counts['orders']} orders, {counts['order_items']} order items, "
            f"{counts['invoices']} invoices, {counts['payments']} payments, "
            f"{counts['reservations']} reservations, {counts['loyalty']} loyalty accounts"
        )


async def _main() -> None:
    async with AsyncSessionLocal() as db:
        await seed(db)


if __name__ == "__main__":
    asyncio.run(_main())
