"""billing coupons loyalty inventory

Revision ID: 05b913f060a9
Revises: ad568d0397ae
Create Date: 2026-07-18 11:36:46.433907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b913f060a9'
down_revision: Union[str, Sequence[str], None] = 'ad568d0397ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('type', sa.Enum('flat', 'percentage', 'bogo', name='coupontypeenum', native_enum=False, length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_coupons_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons')),
    sa.UniqueConstraint('restaurant_id', 'code', name='uq_coupon_code_per_restaurant')
    )
    op.create_index(op.f('ix_coupons_restaurant_id'), 'coupons', ['restaurant_id'], unique=False)
    op.create_table('loyalty_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_loyalty_accounts_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_accounts')),
    sa.UniqueConstraint('restaurant_id', 'phone', name='uq_loyalty_phone_per_restaurant')
    )
    op.create_index(op.f('ix_loyalty_accounts_restaurant_id'), 'loyalty_accounts', ['restaurant_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_suppliers_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_index(op.f('ix_suppliers_restaurant_id'), 'suppliers', ['restaurant_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('stock_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_ingredients_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_ingredients_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients'))
    )
    op.create_index(op.f('ix_ingredients_restaurant_id'), 'ingredients', ['restaurant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coupon_code', sa.String(length=40), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('loyalty_redeemed_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('loyalty_phone', sa.String(length=40), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'partial', 'paid', 'refunded', name='invoicestatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_invoices_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['restaurant_tables.id'], name=op.f('fk_invoices_table_id_restaurant_tables'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index(op.f('ix_invoices_restaurant_id'), 'invoices', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_table_id'), 'invoices', ['table_id'], unique=False)
    op.create_table('invoice_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_orders_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_invoice_orders_order_id_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_orders'))
    )
    op.create_index(op.f('ix_invoice_orders_invoice_id'), 'invoice_orders', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_orders_order_id'), 'invoice_orders', ['order_id'], unique=False)
    op.create_table('menu_item_ingredients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('menu_item_id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_per_serving', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_menu_item_ingredients_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_menu_item_ingredients_menu_item_id_menu_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_ingredients')),
    sa.UniqueConstraint('menu_item_id', 'ingredient_id', name='uq_recipe_line')
    )
    op.create_index(op.f('ix_menu_item_ingredients_ingredient_id'), 'menu_item_ingredients', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_menu_item_ingredients_menu_item_id'), 'menu_item_ingredients', ['menu_item_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.Enum('cash', 'card', 'upi', 'razorpay', name='paymentmethodenum', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='paymentstatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.add_column('site_settings', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('site_settings', sa.Column('loyalty_points_per_currency', sa.Numeric(precision=6, scale=2), nullable=False))
    op.add_column('site_settings', sa.Column('loyalty_redeem_rate', sa.Numeric(precision=6, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'loyalty_redeem_rate')
    op.drop_column('site_settings', 'loyalty_points_per_currency')
    op.drop_column('site_settings', 'tax_rate')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_menu_item_ingredients_menu_item_id'), table_name='menu_item_ingredients')
    op.drop_index(op.f('ix_menu_item_ingredients_ingredient_id'), table_name='menu_item_ingredients')
    op.drop_table('menu_item_ingredients')
    op.drop_index(op.f('ix_invoice_orders_order_id'), table_name='invoice_orders')
    op.drop_index(op.f('ix_invoice_orders_invoice_id'), table_name='invoice_orders')
    op.drop_table('invoice_orders')
    op.drop_index(op.f('ix_invoices_table_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_restaurant_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_ingredients_restaurant_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_suppliers_restaurant_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_loyalty_accounts_restaurant_id'), table_name='loyalty_accounts')
    op.drop_table('loyalty_accounts')
    op.drop_index(op.f('ix_coupons_restaurant_id'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
