"""add hidden_pages to site_settings

Revision ID: c641b24ee320
Revises: 05b913f060a9
Create Date: 2026-07-22 17:57:30.224822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c641b24ee320'
down_revision: Union[str, Sequence[str], None] = '05b913f060a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('hidden_pages', sa.JSON(), nullable=False, server_default='[]'))
    op.alter_column('site_settings', 'hidden_pages', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'hidden_pages')
    # ### end Alembic commands ###
