"""phase 3 multi-tenant: organizations, branch/org scoping

Revision ID: d801df3fcc24
Revises: c641b24ee320
Create Date: 2026-07-22 19:28:05.239882

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd801df3fcc24'
down_revision: Union[str, Sequence[str], None] = 'c641b24ee320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'suspended', name='organizationstatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.add_column('restaurants', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_restaurants_organization_id'), 'restaurants', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_restaurants_organization_id_organizations'), 'restaurants', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.alter_column('users', 'restaurant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_organization_id_organizations'), 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # Backfill: pre-Phase-3 installs have restaurants/users with no
    # organization at all. Link them all to one default Organization so the
    # existing single-tenant login/data keeps working unmodified.
    bind = op.get_bind()
    existing_restaurant = bind.execute(sa.text("SELECT id FROM restaurants LIMIT 1")).fetchone()
    if existing_restaurant:
        org_id = str(uuid.uuid4())
        bind.execute(
            sa.text(
                "INSERT INTO organizations (id, name, slug, status, created_at, updated_at) "
                "VALUES (:id, 'Default Organization', 'default-org', 'active', now(), now())"
            ),
            {"id": org_id},
        )
        bind.execute(sa.text("UPDATE restaurants SET organization_id = :org_id"), {"org_id": org_id})
        bind.execute(
            sa.text("UPDATE users SET organization_id = :org_id WHERE restaurant_id IS NOT NULL"),
            {"org_id": org_id},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_organization_id_organizations'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.alter_column('users', 'restaurant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('users', 'organization_id')
    op.drop_constraint(op.f('fk_restaurants_organization_id_organizations'), 'restaurants', type_='foreignkey')
    op.drop_index(op.f('ix_restaurants_organization_id'), table_name='restaurants')
    op.drop_column('restaurants', 'organization_id')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
