"""phase 4 global menu coupons staff inventory transfers branch archive org branding

Revision ID: 584eead0f022
Revises: d801df3fcc24
Create Date: 2026-07-23 14:52:58.314139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584eead0f022'
down_revision: Union[str, Sequence[str], None] = 'd801df3fcc24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_coupons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('type', sa.Enum('flat', 'percentage', 'bogo', name='coupontypeenum', native_enum=False, length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_global_coupons_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_coupons'))
    )
    op.create_index(op.f('ix_global_coupons_organization_id'), 'global_coupons', ['organization_id'], unique=False)
    op.create_table('global_menu_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('dietary_tags', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_global_menu_items_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_menu_items'))
    )
    op.create_index(op.f('ix_global_menu_items_organization_id'), 'global_menu_items', ['organization_id'], unique=False)
    op.create_table('inventory_transfer_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('from_restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('to_restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'completed', name='transferstatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_restaurant_id'], ['restaurants.id'], name=op.f('fk_inventory_transfer_requests_from_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_inventory_transfer_requests_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_inventory_transfer_requests_requested_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_restaurant_id'], ['restaurants.id'], name=op.f('fk_inventory_transfer_requests_to_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_transfer_requests'))
    )
    op.create_index(op.f('ix_inventory_transfer_requests_from_restaurant_id'), 'inventory_transfer_requests', ['from_restaurant_id'], unique=False)
    op.create_index(op.f('ix_inventory_transfer_requests_organization_id'), 'inventory_transfer_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inventory_transfer_requests_to_restaurant_id'), 'inventory_transfer_requests', ['to_restaurant_id'], unique=False)
    op.add_column('coupons', sa.Column('source_global_coupon_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_coupons_source_global_coupon_id'), 'coupons', ['source_global_coupon_id'], unique=False)
    op.create_foreign_key(op.f('fk_coupons_source_global_coupon_id_global_coupons'), 'coupons', 'global_coupons', ['source_global_coupon_id'], ['id'], ondelete='SET NULL')
    op.add_column('menu_items', sa.Column('source_global_item_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_menu_items_source_global_item_id'), 'menu_items', ['source_global_item_id'], unique=False)
    op.create_foreign_key(op.f('fk_menu_items_source_global_item_id_global_menu_items'), 'menu_items', 'global_menu_items', ['source_global_item_id'], ['id'], ondelete='SET NULL')
    # server_default required on these two: both tables already have rows in
    # the real DB (2 organizations, 3 restaurants), and a NOT NULL column
    # with no default can't be added to a non-empty table.
    op.add_column(
        'organizations',
        sa.Column(
            'plan',
            sa.Enum('trial', 'starter', 'pro', 'enterprise', name='organizationplanenum', native_enum=False, length=20),
            server_default='trial',
            nullable=False,
        ),
    )
    op.add_column('organizations', sa.Column('brand_logo_url', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('brand_primary_color', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('brand_accent_color', sa.String(length=20), nullable=True))
    op.add_column(
        'restaurants',
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'is_active')
    op.drop_column('organizations', 'brand_accent_color')
    op.drop_column('organizations', 'brand_primary_color')
    op.drop_column('organizations', 'brand_logo_url')
    op.drop_column('organizations', 'plan')
    op.drop_constraint(op.f('fk_menu_items_source_global_item_id_global_menu_items'), 'menu_items', type_='foreignkey')
    op.drop_index(op.f('ix_menu_items_source_global_item_id'), table_name='menu_items')
    op.drop_column('menu_items', 'source_global_item_id')
    op.drop_constraint(op.f('fk_coupons_source_global_coupon_id_global_coupons'), 'coupons', type_='foreignkey')
    op.drop_index(op.f('ix_coupons_source_global_coupon_id'), table_name='coupons')
    op.drop_column('coupons', 'source_global_coupon_id')
    op.drop_index(op.f('ix_inventory_transfer_requests_to_restaurant_id'), table_name='inventory_transfer_requests')
    op.drop_index(op.f('ix_inventory_transfer_requests_organization_id'), table_name='inventory_transfer_requests')
    op.drop_index(op.f('ix_inventory_transfer_requests_from_restaurant_id'), table_name='inventory_transfer_requests')
    op.drop_table('inventory_transfer_requests')
    op.drop_index(op.f('ix_global_menu_items_organization_id'), table_name='global_menu_items')
    op.drop_table('global_menu_items')
    op.drop_index(op.f('ix_global_coupons_organization_id'), table_name='global_coupons')
    op.drop_table('global_coupons')
    # ### end Alembic commands ###
